# Generated by Django 5.0.6 on 2024-05-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=7),
        ),
    ]
